version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master

build_script:
  - cmd: dotnet restore src\Vortice.Windows.sln
  - cmd: msbuild /t:Pack /p:Configuration=Release src\SharpDXGI\SharpDXGI.csproj /m
  - cmd: msbuild /t:Pack /p:Configuration=Release src\SharpD3D11\SharpD3D11.csproj /m
  - cmd: msbuild /t:Pack /p:Configuration=Release src\SharpD3D12\SharpD3D12.csproj /m
  - cmd: msbuild /t:Pack /p:Configuration=Release src\SharpD2D1\SharpD2D1.csproj /m

artifacts:
- path: bin\Release\Packages\*.nupkg
  name: Nugets Artifacts

deploy:
- provider: NuGet
  server: https://www.myget.org/F/vortice/api/v2/package
  api_key:
    secure: rVfu/HYGH96xeQfy+gRBC/ovHCheQKTjwIeNIE9HlpkN6e4/YtPUqn5f036pSlmi
  skip_symbols: false
  symbol_server: https://www.myget.org/F/vortice/api/v2/package
  artifact: Nugets Artifacts
