version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master

build:
  project: src/Vortice.Windows.sln
  verbosity: minimal

before_package:
- cmd: dotnet restore src\Vortice.Windows.sln
- cmd: dotnet pack -c Release Vortice.DirectX/Vortice.DirectX.csproj
- cmd: dotnet pack -c Release Vortice.DirectX.Direct3D11/Vortice.DirectX.Direct3D11.csproj
- cmd: dotnet pack -c Release Vortice.DirectX.Direct3D12/Vortice.DirectX.Direct3D12.csproj
- cmd: dotnet pack -c Release Vortice.DirectX.Direct2D/Vortice.DirectX.Direct2D.csproj
- cmd: dotnet pack -c Release Vortice.DirectX.ShaderCompiler/Vortice.DirectX.ShaderCompiler.csproj

artifacts:
- path: bin\Release\Packages\*.nupkg
  name: Nugets Artifacts

deploy:
- provider: NuGet
  server: https://www.myget.org/F/vortice/api/v2/package
  api_key:
    secure: rVfu/HYGH96xeQfy+gRBC/ovHCheQKTjwIeNIE9HlpkN6e4/YtPUqn5f036pSlmi
  skip_symbols: false
  symbol_server: https://www.myget.org/F/vortice/api/v2/package
  artifact: Nugets Artifacts
