trigger:
- master

pool:
  vmImage: windows-2019

variables:
  solution: 'src/Vortice.Windows.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'DotNetCore Installer'
  inputs:
    version: '2.1.403'

- task: NuGetToolInstaller@0
  displayName: 'NuGet Installer'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: config

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
